_target_: src.models.mnist_gan_model.MNISTGANModel

lr: 0.0002
b1: 0.5
b2: 0.999
n_classes: 10
latent_dim: 100
channels: 1
img_size: 32
base_channels: 64

# TODO: instantiate the generator and discriminator objects with Hydra
#       https://hydra.cc/docs/advanced/instantiate_objects/overview/
generator:
  _target_: src.models.modules.generators.CNNGenerator
  n_classes: ${..n_classes}
  latent_dim: ${..latent_dim}
  channels: ${..channels}
  img_size: ${..img_size}
  base_channels: ${..base_channels}
  use_batchnorm: true

discriminator:
  _target_: src.models.modules.discriminators.CNNDiscriminator
  n_classes: ${..n_classes}
  channels: ${..channels}
  img_size: ${..img_size}
  base_channels: ${..base_channels}
  use_spectral_norm: false