_target_: src.models.mnist_gan_model.MNISTGANModel

loss_type: hinge        # {lsgan, hinge}
# TTUR（different G/D's learning rates & betas）
lr_g: 0.0001
lr_d: 0.0002
b1_g: 0.0
b2_g: 0.9
b1_d: 0.0
b2_d: 0.9

# Exponential Moving Average
ema_enabled: true
ema_decay: 0.999

lr: 0.0002
b1: 0.5
b2: 0.999
n_classes: 10
latent_dim: 100
channels: 3
img_size: 64

# TODO: instantiate the generator and discriminator objects with Hydra
#       https://hydra.cc/docs/advanced/instantiate_objects/overview/
generator:
  _target_: src.models.modules.generators.CNNGenerator
  n_classes: ${..n_classes}
  latent_dim: ${..latent_dim}
  channels: ${..channels}
  img_size: ${..img_size}
  base_channels: 128
  use_batchnorm: true

discriminator:
  _target_: src.models.modules.discriminators.CNNDiscriminator
  n_classes: ${..n_classes}
  channels: ${..channels}
  img_size: ${..img_size}
  base_channels: 192
  use_spectral_norm: ture